version: '3'

volumes:
  mariadb-data:
  redis-data:

services:
  mariadb:
    image: mariadb:latest
    container_name: centersis-mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=centersis
      - MYSQL_DATABASE=centersis
      - MYSQL_USER=centersis
      - MYSQL_PASSWORD=centersis

  cache:
    image: redis:4.0-alpine
    container_name: centersis-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  app:
    build: ./docker/php
    container_name: centersis-php
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    links:
      - mariadb
      - cache

  queue:
    build: ./docker/php
    container_name: centersis-queue
    command: php artisan horizon
    volumes:
      - .:/var/www/app
    restart: unless-stopped
    links:
      - mariadb
      - cache

  server:
    image: nginx:alpine
    container_name: centersis-webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    links:
      - app
